### PR TITLE
Parallelising hiccup-based-parser and more

### PR DESCRIPTION
**Pull request by jstepien**
Hi,

Here are 3 patches making hiccup-based-parser parallel and introducing some other minor simplifications. There's some extra discussion in commit messages.

Cheers!

### CODE REVIEW

**Comment by jstepien** [comment]
I've just added 931fdca on top of existing changes. Not only does it bring a minor improvement for long VCS logs, but it also has a noticeable effect on shorter histories. Unfortunately, it doesn't work on OpenJDK 6 because of relying on [Fork/Join](https://docs.oracle.com/javase/tutorial/essential/concurrency/forkjoin.html). Let me know what do you think about it.

**Comment by adamtornhill** [comment]
@jstepien Wonderful - thanks a lot! I'll have a look at your pull request tomorrow. Just one question: any idea how your changes affect memory for large version-control logs? The reason I ask is that it was an issue in the past before I switched to reading the logs chunk by chunk (i.e. parse one commit at a time).

**Comment by jstepien** [comment]
To the best of my knowledge, memory consumption should not increase. Just like on the current master, Instaparse is invoked on single entries and not on the entire history.

I've made some experiments on the current history of Git, totalling 32k commits. It seems that Code Maat is in fact **less** memory hungry now. On the current master the following runs out of memory:

```
java -XX:+UseG1GC -Xmx140m  -jar uberjar.jar -l log  -c git2 -a summary
```

This changeset makes it finish the analysis successfully.

I'm on

```
$ java -version
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by adamtornhill** [comment]
Thanks a lot for the pull request @jstepien - yes, the memory consumption looks good (I've tested and measured with some large logs I've collected over the years).

**Comment by jstepien** [comment]
My pleasure, thanks for merging!

**Pull request merged**
