### PR TITLE
TFS Support

### PR DESCRIPTION
**Pull request by laenas**
Added support for TFS log parsing

### CODE REVIEW

**Comment by adamtornhill** [comment]
@laenas Thanks a lot for your pull request and your well-written code!

I have one concern with TFS regarding its timestamps. I've implemented a similar TFS parser myself only to find out that the dates in the generated log file seem to depend upon the localization settings of the user. This was for the brief TFS log format, but I found out that the dates could be given on multiple different formats and there wasn't any obvious way to override it. I suspect it's the same for the detailed format.

I still want to merge your additions. But would it be possible to:
1. Document that only one time format is supported, and/or
2. Catch a potential unsupported time format and deliver a proper diagnostic to the user?

**Comment by laenas** [comment]
This is my first go-about with Clojure, so it may take me a day, but I'll definitely work on implementing those things.

**Comment by laenas** [comment]
I believe the preceding updates should help clarify current behavioral requirements. 

Would you be opposed to future work that expands the commandline args to take in a format string?

**Comment by adamtornhill** [comment]
Thanks, looks good! It definitely clarifies the limitation.

Yes, I think it would be good with an optional commandline arg to specify a date format string.

**Pull request merged**
